[2022-04-16 18:50:18,582] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: live_coded_gcs_2_bg_dag.bq_ext_2_part_task manual__2022-04-16T18:45:04.028564+00:00 [queued]>
[2022-04-16 18:50:18,591] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: live_coded_gcs_2_bg_dag.bq_ext_2_part_task manual__2022-04-16T18:45:04.028564+00:00 [queued]>
[2022-04-16 18:50:18,592] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-16 18:50:18,593] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2022-04-16 18:50:18,594] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-16 18:50:18,608] {taskinstance.py:1259} INFO - Executing <Task(BigQueryInsertJobOperator): bq_ext_2_part_task> on 2022-04-16 18:45:04.028564+00:00
[2022-04-16 18:50:18,612] {standard_task_runner.py:52} INFO - Started process 2173 to run task
[2022-04-16 18:50:18,616] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'live_coded_gcs_2_bg_dag', 'bq_ext_2_part_task', 'manual__2022-04-16T18:45:04.028564+00:00', '--job-id', '2227', '--raw', '--subdir', 'DAGS_FOLDER/gcs_2_bq_dag.py', '--cfg-path', '/tmp/tmpp1xwidls', '--error-file', '/tmp/tmpshwie0qz']
[2022-04-16 18:50:18,619] {standard_task_runner.py:77} INFO - Job 2227: Subtask bq_ext_2_part_task
[2022-04-16 18:50:18,680] {logging_mixin.py:109} INFO - Running <TaskInstance: live_coded_gcs_2_bg_dag.bq_ext_2_part_task manual__2022-04-16T18:45:04.028564+00:00 [running]> on host 3e228c3601a1
[2022-04-16 18:50:18,745] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=live_coded_gcs_2_bg_dag
AIRFLOW_CTX_TASK_ID=bq_ext_2_part_task
AIRFLOW_CTX_EXECUTION_DATE=2022-04-16T18:45:04.028564+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-16T18:45:04.028564+00:00
[2022-04-16 18:50:18,747] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-16 18:50:18,756] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-16 18:50:18,772] {bigquery.py:1637} INFO - Inserting job ***_live_coded_gcs_2_bg_dag_bq_ext_2_part_task_2022_04_16T18_45_04_028564_00_00_db2d24bb8636978d6b7b8c22385869f8
[2022-04-16 18:50:21,343] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2287, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2253, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1447, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1437, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading table: trips_data_all.external_table, error message: Failed to expand table trips_data_all.external_table with file pattern gs://dtc_data_lake_disco-abacus-332810/raw/yellow_tripdata_2021-01.parquet: matched no files.

(job ID: airflow_live_coded_gcs_2_bg_dag_bq_ext_2_part_task_2022_04_16T18_45_04_028564_00_00_db2d24bb8636978d6b7b8c22385869f8)

                                                                       -----Query Job SQL Follows-----                                                                       

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:CREATE OR REPLACE TABLE trips_data_all.external_table_partitoned         PARTITION BY DATE(tpep_pickup_datetime) AS         SELECT * FROM trips_data_all.external_table;
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2022-04-16 18:50:21,363] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=live_coded_gcs_2_bg_dag, task_id=bq_ext_2_part_task, execution_date=20220416T184504, start_date=20220416T185018, end_date=20220416T185021
[2022-04-16 18:50:21,376] {standard_task_runner.py:92} ERROR - Failed to execute job 2227 for task bq_ext_2_part_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2287, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2253, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1447, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1437, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading table: trips_data_all.external_table, error message: Failed to expand table trips_data_all.external_table with file pattern gs://dtc_data_lake_disco-abacus-332810/raw/yellow_tripdata_2021-01.parquet: matched no files.

(job ID: airflow_live_coded_gcs_2_bg_dag_bq_ext_2_part_task_2022_04_16T18_45_04_028564_00_00_db2d24bb8636978d6b7b8c22385869f8)

                                                                       -----Query Job SQL Follows-----                                                                       

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:CREATE OR REPLACE TABLE trips_data_all.external_table_partitoned         PARTITION BY DATE(tpep_pickup_datetime) AS         SELECT * FROM trips_data_all.external_table;
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2022-04-16 18:50:21,417] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-16 18:50:21,449] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
