[2022-04-14 02:24:30,386] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDAG.ingest scheduled__2022-04-02T06:00:35+00:00 [queued]>
[2022-04-14 02:24:30,397] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDAG.ingest scheduled__2022-04-02T06:00:35+00:00 [queued]>
[2022-04-14 02:24:30,398] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-14 02:24:30,399] {taskinstance.py:1239} INFO - Starting attempt 8 of 8
[2022-04-14 02:24:30,399] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-14 02:24:30,412] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): ingest> on 2022-04-02 06:00:35+00:00
[2022-04-14 02:24:30,418] {standard_task_runner.py:52} INFO - Started process 6915 to run task
[2022-04-14 02:24:30,423] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDAG', 'ingest', 'scheduled__2022-04-02T06:00:35+00:00', '--job-id', '2040', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmp6ej59vbo', '--error-file', '/tmp/tmphgc3xrfd']
[2022-04-14 02:24:30,425] {standard_task_runner.py:77} INFO - Job 2040: Subtask ingest
[2022-04-14 02:24:30,509] {logging_mixin.py:109} INFO - Running <TaskInstance: LocalIngestionDAG.ingest scheduled__2022-04-02T06:00:35+00:00 [running]> on host f13cd06666dc
[2022-04-14 02:24:30,572] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-14 02:24:30,594] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDAG
AIRFLOW_CTX_TASK_ID=ingest
AIRFLOW_CTX_EXECUTION_DATE=2022-04-02T06:00:35+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-02T06:00:35+00:00
[2022-04-14 02:24:30,595] {logging_mixin.py:109} INFO - yellow_taxi_2022_04 /opt/***/output_2022-04.csv 2022-04-02T06:00:35+00:00
[2022-04-14 02:24:30,670] {logging_mixin.py:109} INFO - connection established successfully, inserting data...
[2022-04-14 02:24:30,675] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_script.py", line 30, in ingest_callable
    df.tpep_pickup_datetime = pd.to_datetime(df.tpep_pickup_datetime)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'tpep_pickup_datetime'
[2022-04-14 02:24:30,690] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=LocalIngestionDAG, task_id=ingest, execution_date=20220402T060035, start_date=20220414T022430, end_date=20220414T022430
[2022-04-14 02:24:30,709] {standard_task_runner.py:92} ERROR - Failed to execute job 2040 for task ingest
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_script.py", line 30, in ingest_callable
    df.tpep_pickup_datetime = pd.to_datetime(df.tpep_pickup_datetime)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'tpep_pickup_datetime'
[2022-04-14 02:24:30,758] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-14 02:24:30,798] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
