[2022-04-13 21:55:00,914] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDAG.wget scheduled__2021-11-02T06:00:18+00:00 [queued]>
[2022-04-13 21:55:00,955] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDAG.wget scheduled__2021-11-02T06:00:18+00:00 [queued]>
[2022-04-13 21:55:00,958] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-13 21:55:00,959] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-04-13 21:55:00,960] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-13 21:55:01,001] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): wget> on 2021-11-02 06:00:18+00:00
[2022-04-13 21:55:01,084] {standard_task_runner.py:52} INFO - Started process 6892 to run task
[2022-04-13 21:55:01,093] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDAG', 'wget', 'scheduled__2021-11-02T06:00:18+00:00', '--job-id', '1342', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmp743mjx5n', '--error-file', '/tmp/tmp2g0ar9h8']
[2022-04-13 21:55:01,096] {standard_task_runner.py:77} INFO - Job 1342: Subtask wget
[2022-04-13 21:55:01,252] {logging_mixin.py:109} INFO - Running <TaskInstance: LocalIngestionDAG.wget scheduled__2021-11-02T06:00:18+00:00 [running]> on host 13db72185839
[2022-04-13 21:55:01,400] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDAG
AIRFLOW_CTX_TASK_ID=wget
AIRFLOW_CTX_EXECUTION_DATE=2021-11-02T06:00:18+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-11-02T06:00:18+00:00
[2022-04-13 21:55:01,402] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-04-13 21:55:01,406] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2021-01.csv > /opt/***/output.csv']
[2022-04-13 21:55:01,434] {subprocess.py:85} INFO - Output:
[2022-04-13 22:31:12,988] {subprocess.py:89} INFO - curl: (18) transfer closed with 5385734 bytes remaining to read
[2022-04-13 22:31:13,166] {subprocess.py:93} INFO - Command exited with return code 18
[2022-04-13 22:31:14,745] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 18.
[2022-04-13 22:31:14,871] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=LocalIngestionDAG, task_id=wget, execution_date=20211102T060018, start_date=20220413T215500, end_date=20220413T223114
[2022-04-13 22:31:15,181] {standard_task_runner.py:92} ERROR - Failed to execute job 1342 for task wget
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 18.
[2022-04-13 22:31:15,359] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-13 22:31:15,671] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
