[2022-04-13 14:15:26,985] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2022-04-13T14:15:24.147123+00:00 [queued]>
[2022-04-13 14:15:27,026] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2022-04-13T14:15:24.147123+00:00 [queued]>
[2022-04-13 14:15:27,028] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-13 14:15:27,029] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-04-13 14:15:27,030] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-13 14:15:27,057] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2022-04-13 14:15:24.147123+00:00
[2022-04-13 14:15:27,065] {standard_task_runner.py:52} INFO - Started process 1492 to run task
[2022-04-13 14:15:27,075] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'download_dataset_task', 'manual__2022-04-13T14:15:24.147123+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp5n0qreka', '--error-file', '/tmp/tmp71rusktk']
[2022-04-13 14:15:27,078] {standard_task_runner.py:77} INFO - Job 73: Subtask download_dataset_task
[2022-04-13 14:15:27,203] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2022-04-13T14:15:24.147123+00:00 [running]> on host 45852b52f2a6
[2022-04-13 14:15:27,298] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-04-13T14:15:24.147123+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-13T14:15:24.147123+00:00
[2022-04-13 14:15:27,300] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-04-13 14:15:27,302] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2021-01.csv > /opt/***/yellow_tripdata_2021-01.csv']
[2022-04-13 14:15:27,313] {subprocess.py:85} INFO - Output:
[2022-04-13 14:23:08,085] {local_task_job.py:212} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2022-04-13 14:23:08,112] {process_utils.py:124} INFO - Sending Signals.SIGTERM to group 1492. PIDs of all processes in the group: [1493, 1494, 1492]
[2022-04-13 14:23:08,113] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 1492
[2022-04-13 14:23:08,114] {taskinstance.py:1408} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-04-13 14:23:08,115] {subprocess.py:99} INFO - Sending SIGTERM signal to process group
[2022-04-13 14:23:08,208] {process_utils.py:70} INFO - Process psutil.Process(pid=1493, status='terminated', started='14:15:26') (1493) terminated with exit code None
[2022-04-13 14:23:08,209] {process_utils.py:70} INFO - Process psutil.Process(pid=1492, status='terminated', exitcode=0, started='14:15:26') (1492) terminated with exit code 0
[2022-04-13 14:23:08,210] {process_utils.py:70} INFO - Process psutil.Process(pid=1494, status='terminated', started='14:15:26') (1494) terminated with exit code None
