[2022-04-13 22:28:16,636] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDAG.wget scheduled__2021-12-02T06:00:23+00:00 [queued]>
[2022-04-13 22:28:16,662] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDAG.wget scheduled__2021-12-02T06:00:23+00:00 [queued]>
[2022-04-13 22:28:16,662] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-13 22:28:16,663] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-04-13 22:28:16,663] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-13 22:28:16,704] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): wget> on 2021-12-02 06:00:23+00:00
[2022-04-13 22:28:16,718] {standard_task_runner.py:52} INFO - Started process 9006 to run task
[2022-04-13 22:28:16,724] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDAG', 'wget', 'scheduled__2021-12-02T06:00:23+00:00', '--job-id', '1464', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmp0vou7n7m', '--error-file', '/tmp/tmpourxl_si']
[2022-04-13 22:28:16,731] {standard_task_runner.py:77} INFO - Job 1464: Subtask wget
[2022-04-13 22:28:16,900] {logging_mixin.py:109} INFO - Running <TaskInstance: LocalIngestionDAG.wget scheduled__2021-12-02T06:00:23+00:00 [running]> on host 13db72185839
[2022-04-13 22:28:17,069] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-13 22:28:17,159] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDAG
AIRFLOW_CTX_TASK_ID=wget
AIRFLOW_CTX_EXECUTION_DATE=2021-12-02T06:00:23+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-02T06:00:23+00:00
[2022-04-13 22:28:17,161] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-04-13 22:28:17,163] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2021-12" > /opt/***/output.csv']
[2022-04-13 22:28:17,183] {subprocess.py:85} INFO - Output:
[2022-04-13 22:28:17,189] {subprocess.py:89} INFO - bash: -c: line 0: unexpected EOF while looking for matching `"'
[2022-04-13 22:28:17,189] {subprocess.py:89} INFO - bash: -c: line 1: syntax error: unexpected end of file
[2022-04-13 22:28:17,190] {subprocess.py:93} INFO - Command exited with return code 1
[2022-04-13 22:28:17,799] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-04-13 22:28:17,817] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=LocalIngestionDAG, task_id=wget, execution_date=20211202T060023, start_date=20220413T222816, end_date=20220413T222817
[2022-04-13 22:28:17,872] {standard_task_runner.py:92} ERROR - Failed to execute job 1464 for task wget
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-04-13 22:28:17,921] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-13 22:28:19,200] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
